name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Shellcheck
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck
          shellcheck provision/provision-scripts/*.sh
      - name: Ansible syntax check
        run: |
          sudo apt-get install -y ansible
          ansible-playbook --syntax-check ansible/playbook.yml
